export const users = [
  { id: "u1", name: "Alex Mercer", role: "Sales Manager", email: "alex@petsfolio.com", avatar: "AM" },
  { id: "u2", name: "Sarah Connor", role: "Sales Representative", email: "sarah@petsfolio.com", avatar: "SC" },
  { id: "u3", name: "David Miller", role: "Sales Representative", email: "david@petsfolio.com", avatar: "DM" },
  { id: "u4", name: "Emily Davis", role: "Sales Representative", email: "emily@petsfolio.com", avatar: "ED" }
];

export const services = [
  { id: "s1", name: "Grooming", code: "Grooming", active: true, color: "#2563eb" },
  { id: "s2", name: "Training", code: "Training", active: true, color: "#16a34a" },
  { id: "s3", name: "Walking", code: "Walking", active: true, color: "#ea580c" },
  { id: "s4", name: "Pet Sitting", code: "Pet Sitting", active: true, color: "#db2777" },
  { id: "s5", name: "Pet Insurance", code: "Pet Insurance", active: true, color: "#7c3aed" }
];

export const stages = {
  "Grooming": [
    "New Lead",
    "Inquiry",
    "Appointment Scheduled",
    "Grooming Completed",
    "Repeat Booking"
  ],
  "Training": [
    "New Lead",
    "Consultation",
    "Assessment",
    "Package Discussion",
    "Enrollment",
    "Training Active",
    "Renewal"
  ],
  "Walking": [
    "Lead",
    "Trial Walk",
    "Subscription",
    "Active Customer",
    "Renewal"
  ],
  "Pet Sitting": [
    "Lead",
    "Requirement Discussion",
    "Booking Planned",
    "Service Scheduled",
    "Service Completed",
    "Repeat Booking"
  ],
  "Pet Insurance": [
    "Lead",
    "Quote Shared",
    "Documentation",
    "Comparison",
    "Payment",
    "Policy Issued",
    "Renewal"
  ]
};

// Generate 32 Realistic Dummy Leads
export const initialLeads = [
  {
    id: "lead_1",
    name: "John Doe",
    phone: "9876543210",
    email: "john.doe@gmail.com",
    source: "Meta",
    service: "Grooming",
    stage: "New Lead",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-05-26",
    status: "New",
    leadType: "Client",
    providerService: "",
    petName: "Max",
    petBreed: "Golden Retriever",
    petAge: "2 years",
    notes: "Requires hypoallergenic shampoo. Slightly nervous during nail trimming.",
    createdAt: "2026-05-20",
    value: 120,
    city: "Phoenix",
    preferredContactMethod: "Email",
    petWeight: "23 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_2",
    name: "Alice Smith",
    phone: "9812345678",
    email: "alice.smith@yahoo.com",
    source: "Whatsapp",
    service: "Grooming",
    stage: "Inquiry",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-27",
    status: "Follow Up",
    leadType: "Service Provider",
    providerService: "Grooming",
    petName: "Bella",
    petBreed: "Shih Tzu",
    petAge: "1 year",
    notes: "Inquired about full haircut and de-tangling treatment.",
    createdAt: "2026-05-21",
    value: 95,
    city: "Dallas",
    preferredContactMethod: "SMS",
    petWeight: "22 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_3",
    name: "Robert Johnson",
    phone: "8899776655",
    email: "robert.j@outlook.com",
    source: "Social Media",
    service: "Grooming",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-26",
    status: "Price Issue",
    leadType: "Client",
    providerService: "",
    petName: "Rocky",
    petBreed: "German Shepherd",
    petAge: "3 years",
    notes: "Appointment set for Saturday morning. Needs deshedding treatment.",
    createdAt: "2026-05-18",
    value: 150,
    city: "San Jose",
    preferredContactMethod: "Email",
    petWeight: "20 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_4",
    name: "Emily Brown",
    phone: "7766554433",
    email: "emily.b@hotmail.com",
    source: "Meta",
    service: "Grooming",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-06-15",
    status: "Joined",
    leadType: "Client",
    providerService: "",
    petName: "Daisy",
    petBreed: "Poodle",
    petAge: "4 years",
    notes: "Super friendly. Loved the teddy bear cut. Will need a recall for repeat booking in 3 weeks.",
    createdAt: "2026-05-15",
    value: 110,
    city: "Chicago",
    preferredContactMethod: "WhatsApp",
    petWeight: "50 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_5",
    name: "Michael Davis",
    phone: "6655432110",
    email: "mdavis@corpnet.com",
    source: "Email",
    service: "Grooming",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-28",
    status: "Job Assigned",
    leadType: "Service Provider",
    providerService: "Walking",
    petName: "Charlie",
    petBreed: "Cocker Spaniel",
    petAge: "5 years",
    notes: "Monthly regular grooming customer.",
    createdAt: "2026-04-10",
    value: 100,
    city: "San Antonio",
    preferredContactMethod: "Email",
    petWeight: "17 lbs",
    petMedicalConditions: "Allergies"
  },
  {
    id: "lead_6",
    name: "Jessica Wilson",
    phone: "9988776655",
    email: "jess.wilson@me.com",
    source: "Whatsapp",
    service: "Training",
    assignedTo: "David Miller",
    joinedAt: "2026-05-26",
    status: "New",
    leadType: "Service Provider",
    providerService: "Training",
    petName: "Cooper",
    petBreed: "Labrador Retriever",
    petAge: "6 months",
    notes: "Owner is struggling with potty training and basic crate training.",
    createdAt: "2026-05-25",
    value: 450,
    city: "Chicago",
    preferredContactMethod: "Phone",
    petWeight: "46 lbs",
    petMedicalConditions: "Arthritis"
  },
  {
    id: "lead_7",
    name: "Matthew Martinez",
    phone: "8877665544",
    email: "mmartinez@gmail.com",
    source: "Social Media",
    service: "Training",
    assignedTo: "David Miller",
    joinedAt: "2026-05-25", // Overdue for today's followups helper
    status: "Active",
    petName: "Luna",
    petBreed: "Siberian Husky",
    petAge: "1.5 years",
    notes: "High energy level, pulls excessively on leash. Consultation scheduled to align objectives.",
    createdAt: "2026-05-19",
    value: 600,
    city: "Chicago",
    preferredContactMethod: "Phone",
    petWeight: "33 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_8",
    name: "Amanda Thomas",
    phone: "7788990011",
    email: "amanda.t@yahoo.com",
    source: "Email",
    service: "Training",
    assignedTo: "David Miller",
    joinedAt: "2026-05-29",
    status: "Active",
    petName: "Milo",
    petBreed: "Beagle",
    petAge: "8 months",
    notes: "Completed basic initial assessment. Treats motivated but easily distracted.",
    createdAt: "2026-05-16",
    value: 550,
    city: "Philadelphia",
    preferredContactMethod: "WhatsApp",
    petWeight: "12 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_9",
    name: "James Taylor",
    phone: "9911223344",
    email: "jtaylor@outlook.com",
    source: "Meta",
    service: "Training",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-05-27",
    status: "Active",
    petName: "Oliver",
    petBreed: "French Bulldog",
    petAge: "2 years",
    notes: "Discussing the 6-week behavior modification package. Hesitant on pricing.",
    createdAt: "2026-05-14",
    value: 800,
    city: "San Jose",
    preferredContactMethod: "Phone",
    petWeight: "31 lbs",
    petMedicalConditions: "Anxiety"
  },
  {
    id: "lead_10",
    name: "Sarah Jenkins",
    phone: "8822334455",
    email: "sjenkins@gmail.com",
    source: "Whatsapp",
    service: "Training",
    assignedTo: "David Miller",
    joinedAt: "2026-05-30",
    status: "Active",
    petName: "Lola",
    petBreed: "Pug",
    petAge: "1 year",
    notes: "Enrolled in puppy socialization classes. Payment structure finalized.",
    createdAt: "2026-05-12",
    value: 350,
    city: "New York",
    preferredContactMethod: "SMS",
    petWeight: "47 lbs",
    petMedicalConditions: "Diabetes"
  },
  {
    id: "lead_11",
    name: "David White",
    phone: "7733445566",
    email: "dwhite@hotmail.com",
    source: "Email",
    service: "Training",
    assignedTo: "David Miller",
    joinedAt: "2026-05-26",
    status: "Active",
    petName: "Teddy",
    petBreed: "Goldendoodle",
    petAge: "10 months",
    notes: "Active in Group Canine Good Citizen course. Making fast progress.",
    createdAt: "2026-05-01",
    value: 500,
    city: "Houston",
    preferredContactMethod: "Email",
    petWeight: "22 lbs",
    petMedicalConditions: "Diabetes"
  },
  {
    id: "lead_12",
    name: "Lisa Harris",
    phone: "6644556677",
    email: "lharris@gmail.com",
    source: "Email",
    service: "Training",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-05-28",
    status: "Active",
    petName: "Zeus",
    petBreed: "Rottweiler",
    petAge: "3 years",
    notes: "Agility stage 1 completed. Offering 15% discount for Agility Stage 2 renewal.",
    createdAt: "2026-03-15",
    value: 450,
    city: "San Diego",
    preferredContactMethod: "WhatsApp",
    petWeight: "43 lbs",
    petMedicalConditions: "Allergies"
  },
  {
    id: "lead_13",
    name: "Kevin Martin",
    phone: "9955667788",
    email: "kmartin@yahoo.com",
    source: "Meta",
    service: "Walking",
    assignedTo: "David Miller",
    joinedAt: "2026-05-26",
    status: "Active",
    petName: "Winston",
    petBreed: "English Bulldog",
    petAge: "4 years",
    notes: "Needs 30-minute slow paced daily walks due to breathing characteristics.",
    createdAt: "2026-05-24",
    value: 180,
    city: "Dallas",
    preferredContactMethod: "WhatsApp",
    petWeight: "31 lbs",
    petMedicalConditions: "Allergies"
  },
  {
    id: "lead_14",
    name: "Rachel Clark",
    phone: "8866778899",
    email: "rclark@me.com",
    source: "Social Media",
    service: "Walking",
    assignedTo: "David Miller",
    joinedAt: "2026-05-27",
    status: "Active",
    petName: "Coco",
    petBreed: "Chihuahua",
    petAge: "2 years",
    notes: "Trial walk scheduled for tomorrow afternoon. Reactive to large dogs.",
    createdAt: "2026-05-22",
    value: 20,
    city: "Chicago",
    preferredContactMethod: "WhatsApp",
    petWeight: "45 lbs",
    petMedicalConditions: "Arthritis"
  },
  {
    id: "lead_15",
    name: "Brian Rodriguez",
    phone: "7777888899",
    email: "brodriguez@gmail.com",
    source: "Whatsapp",
    service: "Walking",
    assignedTo: "David Miller",
    joinedAt: "2026-05-28",
    status: "Active",
    petName: "Gizmo",
    petBreed: "Boston Terrier",
    petAge: "1.5 years",
    notes: "Enrolling in Mon-Wed-Fri walker subscription package.",
    createdAt: "2026-05-18",
    value: 240,
    city: "Dallas",
    preferredContactMethod: "WhatsApp",
    petWeight: "18 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_16",
    name: "Megan Lewis",
    phone: "8888999900",
    email: "mlewis@corp.com",
    source: "Meta",
    service: "Walking",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-06-01",
    status: "Active",
    petName: "Tucker",
    petBreed: "Australian Shepherd",
    petAge: "3 years",
    notes: "Regular 5-day / week energetic walker customer. Handled by Walker Sam.",
    createdAt: "2026-04-05",
    value: 360,
    city: "San Antonio",
    preferredContactMethod: "Phone",
    petWeight: "27 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_17",
    name: "Steven Walker",
    phone: "9999000011",
    email: "swalker@outlook.com",
    source: "Social Media",
    service: "Walking",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-05-24", // Overdue
    status: "Active",
    petName: "Ruby",
    petBreed: "Boxer",
    petAge: "4 years",
    notes: "Monthly subscription ending on May 28. Needs review for renewal discount.",
    createdAt: "2026-04-20",
    value: 300,
    city: "Chicago",
    preferredContactMethod: "SMS",
    petWeight: "27 lbs",
    petMedicalConditions: "Anxiety"
  },
  {
    id: "lead_18",
    name: "Laura Hall",
    phone: "7788001122",
    email: "lhall@gmail.com",
    source: "Email",
    service: "Pet Sitting",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-26",
    status: "Active",
    petName: "Simba",
    petBreed: "Maine Coon Cat",
    petAge: "2 years",
    notes: "Needs feeding and litter cleaning twice daily from June 10 to June 15.",
    createdAt: "2026-05-24",
    value: 200,
    city: "Los Angeles",
    preferredContactMethod: "SMS",
    petWeight: "23 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_19",
    name: "Daniel Allen",
    phone: "8899112233",
    email: "dallen@company.org",
    source: "Meta",
    service: "Pet Sitting",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-27",
    status: "Active",
    petName: "Chloe",
    petBreed: "Persian Cat",
    petAge: "5 years",
    notes: "Requires administration of insulin shots in the evening. Discussing safety criteria.",
    createdAt: "2026-05-21",
    value: 350,
    city: "San Antonio",
    preferredContactMethod: "WhatsApp",
    petWeight: "38 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_20",
    name: "Ashley Young",
    phone: "6677112233",
    email: "ayoung@gmail.com",
    source: "Whatsapp",
    service: "Pet Sitting",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-05-28",
    status: "Active",
    petName: "Ziggy",
    petBreed: "Border Collie",
    petAge: "2 years",
    notes: "Overnight house sitting planned for 4 nights during 4th of July week.",
    createdAt: "2026-05-18",
    value: 500,
    city: "Dallas",
    preferredContactMethod: "WhatsApp",
    petWeight: "54 lbs",
    petMedicalConditions: "Diabetes"
  },
  {
    id: "lead_21",
    name: "Joseph King",
    phone: "9911559922",
    email: "jking@yahoo.com",
    source: "Social Media",
    service: "Pet Sitting",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-26",
    status: "Active",
    petName: "Minnie",
    petBreed: "Maltese",
    petAge: "6 years",
    notes: "Scheduled block of 3 days. Keys collected and home orientation done.",
    createdAt: "2026-05-10",
    value: 180,
    city: "Philadelphia",
    preferredContactMethod: "WhatsApp",
    petWeight: "38 lbs",
    petMedicalConditions: "Allergies"
  },
  {
    id: "lead_22",
    name: "Katelyn Wright",
    phone: "8822660011",
    email: "kwright@outlook.com",
    source: "Meta",
    service: "Pet Sitting",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-06-05",
    status: "Active",
    petName: "Duke",
    petBreed: "Doberman",
    petAge: "4 years",
    notes: "Pet sitting successfully completed. Owner left 5-star review.",
    createdAt: "2026-05-05",
    value: 400,
    city: "Chicago",
    preferredContactMethod: "WhatsApp",
    petWeight: "55 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_23",
    name: "William Scott",
    phone: "7733551122",
    email: "wscott@yahoo.com",
    source: "Email",
    service: "Pet Sitting",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-05-28",
    status: "Active",
    petName: "Harley",
    petBreed: "Great Dane",
    petAge: "3 years",
    notes: "Regular vacation sitter. Booking again for mid-June weekend.",
    createdAt: "2026-04-12",
    value: 300,
    city: "Dallas",
    preferredContactMethod: "WhatsApp",
    petWeight: "37 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_24",
    name: "Elizabeth Green",
    phone: "9944772211",
    email: "egreen@gmail.com",
    source: "Meta",
    service: "Pet Insurance",
    assignedTo: "Emily Davis",
    joinedAt: "2026-05-26",
    status: "Active",
    petName: "Nala",
    petBreed: "Ragdoll Cat",
    petAge: "5 months",
    notes: "Young kitten, owner wants to lock in a premium coverage starting early.",
    createdAt: "2026-05-24",
    value: 45,
    city: "Philadelphia",
    preferredContactMethod: "WhatsApp",
    petWeight: "20 lbs",
    petMedicalConditions: "Anxiety"
  },
  {
    id: "lead_25",
    name: "Thomas Baker",
    phone: "8855883344",
    email: "tbaker@comcast.net",
    source: "Email",
    service: "Pet Insurance",
    assignedTo: "Emily Davis",
    joinedAt: "2026-05-27",
    status: "Active",
    petName: "Buster",
    petBreed: "Boxer",
    petAge: "5 years",
    notes: "Shared quote for $5,000 annual coverage with $250 deductible. Waiting for response.",
    createdAt: "2026-05-19",
    value: 55,
    city: "Philadelphia",
    preferredContactMethod: "WhatsApp",
    petWeight: "31 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_26",
    name: "Charles Adams",
    phone: "7766991100",
    email: "cadams@gmail.com",
    source: "Whatsapp",
    service: "Pet Insurance",
    assignedTo: "Emily Davis",
    joinedAt: "2026-05-26",
    status: "Active",
    petName: "Oreo",
    petBreed: "Border Collie",
    petAge: "2 years",
    notes: "Owner uploading medical history documents to check for pre-existing conditions exclusions.",
    createdAt: "2026-05-14",
    value: 50,
    city: "Dallas",
    preferredContactMethod: "WhatsApp",
    petWeight: "59 lbs",
    petMedicalConditions: "Arthritis"
  },
  {
    id: "lead_27",
    name: "Patricia Nelson",
    phone: "9900334466",
    email: "pnelson@me.com",
    source: "Meta",
    service: "Pet Insurance",
    assignedTo: "Emily Davis",
    joinedAt: "2026-05-28",
    status: "Active",
    petName: "Zoe",
    petBreed: "Yorkshire Terrier",
    petAge: "6 years",
    notes: "Comparing our comprehensive premium cover against competitor's base-tier budget plan.",
    createdAt: "2026-05-15",
    value: 65,
    city: "Chicago",
    preferredContactMethod: "SMS",
    petWeight: "30 lbs",
    petMedicalConditions: "Allergies"
  },
  {
    id: "lead_28",
    name: "George Carter",
    phone: "8844885522",
    email: "gcarter@yahoo.com",
    source: "Social Media",
    service: "Pet Insurance",
    assignedTo: "Alex Mercer",
    joinedAt: "2026-05-26",
    status: "Active",
    petName: "Rex",
    petBreed: "Siberian Husky",
    petAge: "1 year",
    notes: "Approved proposal. Sent secure payment link. Waiting for transaction execution.",
    createdAt: "2026-05-10",
    value: 70,
    city: "San Diego",
    preferredContactMethod: "SMS",
    petWeight: "23 lbs",
    petMedicalConditions: "Anxiety"
  },
  {
    id: "lead_29",
    name: "Donna Mitchell",
    phone: "7755998811",
    email: "dmitchell@live.com",
    source: "Email",
    service: "Pet Insurance",
    assignedTo: "Emily Davis",
    joinedAt: "2026-11-26",
    status: "Closed Won",
    petName: "Rusty",
    petBreed: "Irish Setter",
    petAge: "3 years",
    notes: "Policy PI-99238 issued. Customer onboarding packet dispatched.",
    createdAt: "2026-05-05",
    value: 80,
    city: "Phoenix",
    preferredContactMethod: "SMS",
    petWeight: "12 lbs",
    petMedicalConditions: "Anxiety"
  },
  {
    id: "lead_30",
    name: "Kenneth Perez",
    phone: "9900228833",
    email: "kperez@gmail.com",
    source: "Email",
    service: "Pet Insurance",
    assignedTo: "Emily Davis",
    joinedAt: "2026-05-20", // Overdue renewal
    status: "Active",
    petName: "Bear",
    petBreed: "Newfoundland",
    petAge: "5 years",
    notes: "Annual policy expiring soon on June 5th. Initiating renewal proposal with premium incentive.",
    createdAt: "2025-05-20",
    value: 90,
    city: "Los Angeles",
    preferredContactMethod: "Email",
    petWeight: "39 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_31",
    name: "Carol Roberts",
    phone: "8855110033",
    email: "croberts@gmail.com",
    source: "Whatsapp",
    service: "Grooming",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-29",
    status: "Active",
    petName: "Rosie",
    petBreed: "Bichon Frise",
    petAge: "6 months",
    notes: "Puppy's first grooming session. Owner is very protective, requested extra caring handling.",
    createdAt: "2026-05-25",
    value: 85,
    city: "San Antonio",
    preferredContactMethod: "WhatsApp",
    petWeight: "24 lbs",
    petMedicalConditions: "Diabetes"
  },
  {
    id: "lead_32",
    name: "Edward Evans",
    phone: "7766110044",
    email: "eevans@yahoo.com",
    source: "Social Media",
    service: "Walking",
    assignedTo: "David Miller",
    joinedAt: "2026-06-02",
    status: "Closed Won",
    petName: "Penny",
    petBreed: "Dachshund",
    petAge: "2 years",
    notes: "Highly energetic. Closed won walking service with 3 rides per week.",
    createdAt: "2026-04-18",
    value: 120,
    city: "San Diego",
    preferredContactMethod: "WhatsApp",
    petWeight: "16 lbs",
    petMedicalConditions: "Arthritis"
  },
  {
    id: "lead_33",
    name: "Clara Hughes",
    phone: "9123456789",
    email: "clara.h@gmail.com",
    source: "Meta",
    service: "Grooming",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-28",
    status: "New",
    leadType: "Client",
    providerService: "",
    petName: "Oliver",
    petBreed: "Poodle",
    petAge: "10 months",
    notes: "Client needs standard breed cut for puppy.",
    createdAt: "2026-05-26",
    value: 90,
    city: "San Diego",
    preferredContactMethod: "Phone",
    petWeight: "54 lbs",
    petMedicalConditions: "Diabetes"
  },
  {
    id: "lead_34",
    name: "Nathan Drake",
    phone: "9234567890",
    email: "drake@unmapped.com",
    source: "Whatsapp",
    service: "Training",
    assignedTo: "Sarah Connor",
    joinedAt: "2026-05-29",
    status: "New",
    leadType: "Service Provider",
    providerService: "Training",
    petName: "Sully",
    petBreed: "Boxer",
    petAge: "3 years",
    notes: "Professional trainer applying to join the network as service partner.",
    createdAt: "2026-05-26",
    value: 0,
    city: "Chicago",
    preferredContactMethod: "Email",
    petWeight: "14 lbs",
    petMedicalConditions: "Allergies"
  },
  {
    id: "lead_35",
    name: "Sophie Turner",
    phone: "9345678901",
    email: "sophie.t@gmail.com",
    source: "Social Media",
    service: "Walking",
    assignedTo: "David Miller",
    joinedAt: "2026-05-27",
    status: "New",
    leadType: "Client",
    providerService: "",
    petName: "Lady",
    petBreed: "Cocker Spaniel",
    petAge: "4 years",
    notes: "Client requesting 2 morning walks per day starting next week.",
    createdAt: "2026-05-26",
    value: 180,
    city: "San Diego",
    preferredContactMethod: "SMS",
    petWeight: "56 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_36",
    name: "Marcus Vance",
    phone: "9456789012",
    email: "marcus@vancewalks.com",
    source: "Email",
    service: "Walking",
    assignedTo: "David Miller",
    joinedAt: "2026-05-28",
    status: "New",
    leadType: "Service Provider",
    providerService: "Walking",
    petName: "Buddy",
    petBreed: "Labrador",
    petAge: "2 years",
    notes: "Looking to onboard as an experienced pet walker for premium routes.",
    createdAt: "2026-05-26",
    value: 0,
    city: "San Antonio",
    preferredContactMethod: "Phone",
    petWeight: "24 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_37",
    name: "Lily Evans",
    phone: "9567890123",
    email: "lily.e@hogwarts.edu",
    source: "Email",
    service: "Pet Sitting",
    assignedTo: "Emily Davis",
    joinedAt: "2026-05-30",
    status: "New",
    leadType: "Client",
    providerService: "",
    petName: "Snitch",
    petBreed: "Siamese Cat",
    petAge: "6 years",
    notes: "In-home pet parenting requested for 5 days of vacation.",
    createdAt: "2026-05-26",
    value: 250,
    city: "Los Angeles",
    preferredContactMethod: "SMS",
    petWeight: "54 lbs",
    petMedicalConditions: "None"
  },
  {
    id: "lead_38",
    name: "Julian Assange",
    phone: "9678901234",
    email: "julian@wikipets.org",
    source: "Meta",
    service: "Grooming",
    assignedTo: "Emily Davis",
    joinedAt: "2026-05-29",
    status: "New",
    leadType: "Service Provider",
    providerService: "Grooming",
    petName: "Leaks",
    petBreed: "Beagle",
    petAge: "5 years",
    notes: "Part-time self-employed groomer seeking subcontract shifts.",
    createdAt: "2026-05-26",
    value: 0,
    city: "New York",
    preferredContactMethod: "WhatsApp",
    petWeight: "39 lbs",
    petMedicalConditions: "Anxiety"
  }
];

export const initialFollowups = [
  { id: "fw1", leadId: "lead_1", leadName: "John Doe", type: "Call", date: "2026-05-26", time: "10:30 AM", priority: "High", done: false, notes: "Call to confirm Grooming appointment scheduled.", petName: "Max" },
  { id: "fw2", leadId: "lead_6", leadName: "Jessica Wilson", type: "WhatsApp", date: "2026-05-26", time: "01:00 PM", priority: "Medium", done: false, notes: "Ping on WhatsApp about training schedules.", petName: "Cooper" },
  { id: "fw3", leadId: "lead_13", leadName: "Kevin Martin", type: "Email", date: "2026-05-26", time: "03:00 PM", priority: "Medium", done: false, notes: "Send walking pricing matrix details.", petName: "Winston" },
  { id: "fw4", leadId: "lead_7", leadName: "Matthew Martinez", type: "Meeting", date: "2026-05-25", time: "11:00 AM", priority: "High", done: false, notes: "Conduct Training Assessment consultation.", petName: "Luna" }, // Overdue
  { id: "fw5", leadId: "lead_17", leadName: "Steven Walker", type: "Call", date: "2026-05-24", time: "04:30 PM", priority: "High", done: false, notes: "Call to discuss walking subscription renewal.", petName: "Ruby" }, // Overdue
  { id: "fw6", leadId: "lead_2", leadName: "Alice Smith", type: "WhatsApp", date: "2026-05-27", time: "11:30 AM", priority: "Low", done: false, notes: "Check schedule for grooming haircut appointment.", petName: "Bella" },
  { id: "fw7", leadId: "lead_22", leadName: "Katelyn Wright", type: "Email", date: "2026-05-10", time: "02:00 PM", priority: "Low", done: true, notes: "Sent thank you note and review prompt.", petName: "Duke" } // Completed
];

export const initialActivities = [
  { id: "act1", leadId: "lead_1", leadName: "John Doe", type: "Stage Changed", content: "Stage updated from Inquiry to Appointment Scheduled by Alex Mercer", date: "2026-05-25T14:30:11Z", author: "Alex Mercer" },
  { id: "act2", leadId: "lead_6", leadName: "Jessica Wilson", type: "Lead Created", content: "Lead created via Whatsapp ad integration.", date: "2026-05-25T09:12:00Z", author: "System" },
  { id: "act3", leadId: "lead_29", leadName: "Donna Mitchell", type: "Policy Issued", content: "Policy documentation uploaded, policy active.", date: "2026-05-24T16:45:00Z", author: "Emily Davis" },
  { id: "act4", leadId: "lead_3", leadName: "Robert Johnson", type: "Note Added", content: "Customer requested a warm air blow dryer instead of cage dryer.", date: "2026-05-24T11:20:00Z", author: "Sarah Connor" },
  { id: "act5", leadId: "lead_15", leadName: "Brian Rodriguez", type: "Call Completed", content: "Discussed subscription pricing options. Client seems positive.", date: "2026-05-23T15:10:00Z", author: "David Miller" }
];

export const initialNotifications = [
  { id: "nt1", type: "followup_overdue", title: "Follow-up Overdue", message: "Walk Renewal follow-up with Steven Walker (Ruby) is overdue since 2026-05-24.", time: "2 hours ago", read: false },
  { id: "nt2", type: "lead_inactive", title: "Inactive Lead Warning", message: "Lead Kenneth Perez has had no activity for over 6 days.", time: "4 hours ago", read: false },
  { id: "nt3", type: "insurance_renewal", title: "Insurance Renewal Due", message: "Kenneth Perez's Siberian Husky (Bear) policy expires in 10 days.", time: "1 day ago", read: false },
  { id: "nt4", type: "grooming_reminder", title: "Grooming Appointment Reminder", message: "Robert Johnson (Rocky) tomorrow scheduled at 10:00 AM.", time: "1 day ago", read: true },
  { id: "nt5", type: "walking_expiring", title: "Walking Subscription Expiring", message: "Steven Walker walking subscription expiring in 2 days.", time: "2 days ago", read: true }
];

export const leadSources = [
  { name: "Meta", count: 12 },
  { name: "Whatsapp", count: 9 },
  { name: "Social Media", count: 6 },
  { name: "Email", count: 3 },
  { name: "Email", count: 2 }
];
